from app import app
from backend.models import db, Product, Dish, DishIngredient


def initialize_database():
    """
    Ініціалізує базу даних:
    1. створює таблиці;
    2. заповнює продукти;
    3. заповнює страви;
    4. створює зв'язки між стравами та продуктами.
    """

    with app.app_context():
        print("Ініціалізація бази даних...")

        db.create_all()
        print("Таблиці створено або вже існують.")

        if Product.query.first():
            print("Продукти вже є в базі. Повторне заповнення не виконується.")
            return

        products_data = [
            Product(
                name="Куряче філе",
                calories_100g=165,
                protein_100g=31,
                fat_100g=3.6,
                carbs_100g=0,
                vit_a_mcg=13,
                vit_c_mg=0,
                vit_d_mcg=0,
                vit_e_mg=0.3,
                vit_k_mcg=0,
                vit_b1_mg=0.07,
                vit_b2_mg=0.12,
                vit_b6_mg=0.6,
                vit_b12_mcg=0.3,
                iron_mg=1,
                calcium_mg=15,
                magnesium_mg=29,
                zinc_mg=1,
            ),
            Product(
                name="Лосось",
                calories_100g=208,
                protein_100g=20,
                fat_100g=13,
                carbs_100g=0,
                vit_a_mcg=40,
                vit_c_mg=0,
                vit_d_mcg=12,
                vit_e_mg=2,
                vit_k_mcg=0,
                vit_b1_mg=0.2,
                vit_b2_mg=0.4,
                vit_b6_mg=0.8,
                vit_b12_mcg=3.2,
                iron_mg=0.8,
                calcium_mg=9,
                magnesium_mg=27,
                zinc_mg=0.6,
            ),
            Product(
                name="Яйце куряче",
                calories_100g=155,
                protein_100g=13,
                fat_100g=11,
                carbs_100g=1.1,
                vit_a_mcg=160,
                vit_c_mg=0,
                vit_d_mcg=2,
                vit_e_mg=1.1,
                vit_k_mcg=0.3,
                vit_b1_mg=0.04,
                vit_b2_mg=0.45,
                vit_b6_mg=0.17,
                vit_b12_mcg=1.1,
                iron_mg=1.8,
                calcium_mg=50,
                magnesium_mg=10,
                zinc_mg=1.3,
            ),
            Product(
                name="Броколі",
                calories_100g=34,
                protein_100g=2.8,
                fat_100g=0.4,
                carbs_100g=6.6,
                vit_a_mcg=31,
                vit_c_mg=89,
                vit_d_mcg=0,
                vit_e_mg=0.8,
                vit_k_mcg=102,
                vit_b1_mg=0.07,
                vit_b2_mg=0.12,
                vit_b6_mg=0.18,
                vit_b12_mcg=0,
                iron_mg=0.7,
                calcium_mg=47,
                magnesium_mg=21,
                zinc_mg=0.4,
            ),
            Product(
                name="Шпинат",
                calories_100g=23,
                protein_100g=2.9,
                fat_100g=0.4,
                carbs_100g=3.6,
                vit_a_mcg=469,
                vit_c_mg=28,
                vit_d_mcg=0,
                vit_e_mg=2,
                vit_k_mcg=483,
                vit_b1_mg=0.08,
                vit_b2_mg=0.19,
                vit_b6_mg=0.2,
                vit_b12_mcg=0,
                iron_mg=2.7,
                calcium_mg=99,
                magnesium_mg=79,
                zinc_mg=0.5,
            ),
            Product(
                name="Морква",
                calories_100g=41,
                protein_100g=0.9,
                fat_100g=0.2,
                carbs_100g=10,
                vit_a_mcg=835,
                vit_c_mg=6,
                vit_d_mcg=0,
                vit_e_mg=0.7,
                vit_k_mcg=13,
                vit_b1_mg=0.07,
                vit_b2_mg=0.06,
                vit_b6_mg=0.14,
                vit_b12_mcg=0,
                iron_mg=0.3,
                calcium_mg=33,
                magnesium_mg=12,
                zinc_mg=0.2,
            ),
            Product(
                name="Перець болгарський",
                calories_100g=31,
                protein_100g=1,
                fat_100g=0.3,
                carbs_100g=6,
                vit_a_mcg=157,
                vit_c_mg=128,
                vit_d_mcg=0,
                vit_e_mg=1.6,
                vit_k_mcg=5,
                vit_b1_mg=0.05,
                vit_b2_mg=0.09,
                vit_b6_mg=0.29,
                vit_b12_mcg=0,
                iron_mg=0.4,
                calcium_mg=7,
                magnesium_mg=12,
                zinc_mg=0.3,
            ),
            Product(
                name="Гречка",
                calories_100g=343,
                protein_100g=13,
                fat_100g=3.4,
                carbs_100g=72,
                vit_a_mcg=0,
                vit_c_mg=0,
                vit_d_mcg=0,
                vit_e_mg=0.8,
                vit_k_mcg=7,
                vit_b1_mg=0.1,
                vit_b2_mg=0.4,
                vit_b6_mg=0.2,
                vit_b12_mcg=0,
                iron_mg=2.2,
                calcium_mg=18,
                magnesium_mg=231,
                zinc_mg=2.4,
            ),
            Product(
                name="Рис бурий",
                calories_100g=111,
                protein_100g=2.6,
                fat_100g=0.9,
                carbs_100g=23,
                vit_a_mcg=0,
                vit_c_mg=0,
                vit_d_mcg=0,
                vit_e_mg=0.1,
                vit_k_mcg=0.2,
                vit_b1_mg=0.1,
                vit_b2_mg=0.01,
                vit_b6_mg=0.15,
                vit_b12_mcg=0,
                iron_mg=0.6,
                calcium_mg=10,
                magnesium_mg=43,
                zinc_mg=0.7,
            ),
            Product(
                name="Вівсянка",
                calories_100g=389,
                protein_100g=17,
                fat_100g=7,
                carbs_100g=66,
                vit_a_mcg=0,
                vit_c_mg=0,
                vit_d_mcg=0,
                vit_e_mg=0.4,
                vit_k_mcg=2,
                vit_b1_mg=0.76,
                vit_b2_mg=0.14,
                vit_b6_mg=0.12,
                vit_b12_mcg=0,
                iron_mg=4.7,
                calcium_mg=54,
                magnesium_mg=177,
                zinc_mg=4,
            ),
            Product(
                name="Сир кисломолочний",
                calories_100g=121,
                protein_100g=17,
                fat_100g=5,
                carbs_100g=3,
                vit_a_mcg=36,
                vit_c_mg=0,
                vit_d_mcg=0.1,
                vit_e_mg=0.1,
                vit_k_mcg=0,
                vit_b1_mg=0.03,
                vit_b2_mg=0.3,
                vit_b6_mg=0.05,
                vit_b12_mcg=0.8,
                iron_mg=0.2,
                calcium_mg=120,
                magnesium_mg=11,
                zinc_mg=0.4,
            ),
            Product(
                name="Йогурт натуральний",
                calories_100g=61,
                protein_100g=3.5,
                fat_100g=3.3,
                carbs_100g=4.7,
                vit_a_mcg=27,
                vit_c_mg=0.5,
                vit_d_mcg=0.1,
                vit_e_mg=0.1,
                vit_k_mcg=0.2,
                vit_b1_mg=0.04,
                vit_b2_mg=0.14,
                vit_b6_mg=0.03,
                vit_b12_mcg=0.4,
                iron_mg=0.1,
                calcium_mg=120,
                magnesium_mg=12,
                zinc_mg=0.6,
            ),
            Product(
                name="Банан",
                calories_100g=89,
                protein_100g=1.1,
                fat_100g=0.3,
                carbs_100g=23,
                vit_a_mcg=3,
                vit_c_mg=9,
                vit_d_mcg=0,
                vit_e_mg=0.1,
                vit_k_mcg=0.5,
                vit_b1_mg=0.03,
                vit_b2_mg=0.07,
                vit_b6_mg=0.37,
                vit_b12_mcg=0,
                iron_mg=0.3,
                calcium_mg=5,
                magnesium_mg=27,
                zinc_mg=0.2,
            ),
            Product(
                name="Яблуко",
                calories_100g=52,
                protein_100g=0.3,
                fat_100g=0.2,
                carbs_100g=14,
                vit_a_mcg=3,
                vit_c_mg=5,
                vit_d_mcg=0,
                vit_e_mg=0.2,
                vit_k_mcg=2,
                vit_b1_mg=0.02,
                vit_b2_mg=0.03,
                vit_b6_mg=0.04,
                vit_b12_mcg=0,
                iron_mg=0.1,
                calcium_mg=6,
                magnesium_mg=5,
                zinc_mg=0.04,
            ),
            Product(
                name="Оливкова олія",
                calories_100g=884,
                protein_100g=0,
                fat_100g=100,
                carbs_100g=0,
                vit_a_mcg=0,
                vit_c_mg=0,
                vit_d_mcg=0,
                vit_e_mg=14,
                vit_k_mcg=60,
                vit_b1_mg=0,
                vit_b2_mg=0,
                vit_b6_mg=0,
                vit_b12_mcg=0,
                iron_mg=0.6,
                calcium_mg=1,
                magnesium_mg=0,
                zinc_mg=0,
            ),
        ]
        extra_dislike_products = [
            "Молоко", "Кефір", "Сметана", "Вершки", "Масло вершкове", "Сир твердий",
            "Плавлений сир", "Моцарела", "Фета", "Бринза",

            "Свинина", "Яловичина", "Індичка", "Качка", "Печінка куряча",
            "Печінка яловича", "Ковбаса", "Сосиски", "Шинка", "Бекон",

            "Тунець", "Скумбрія", "Оселедець", "Сардини", "Креветки", "Кальмари",
            "Мідії", "Крабові палички",

            "Картопля", "Помідор", "Огірок", "Цибуля", "Часник", "Капуста",
            "Цвітна капуста", "Кабачок", "Баклажан", "Гарбуз", "Буряк",
            "Кукурудза", "Горошок", "Квасоля", "Нут", "Сочевиця",

            "Апельсин", "Мандарин", "Лимон", "Грейпфрут", "Ківі", "Полуниця",
            "Малина", "Чорниця", "Виноград", "Груша", "Персик", "Абрикос",
            "Слива", "Ананас", "Манго", "Авокадо",

            "Пшениця", "Булгур", "Кускус", "Макарони", "Білий рис", "Манка",
            "Перлова крупа", "Хліб білий", "Хліб житній", "Лаваш",

            "Арахіс", "Мигдаль", "Волоські горіхи", "Фундук", "Кешʼю",
            "Фісташки", "Насіння соняшника", "Насіння гарбуза", "Кунжут", "Льон",

            "Мед", "Цукор", "Шоколад", "Печиво", "Вафлі", "Торт", "Морозиво",
            "Згущене молоко", "Джем", "Маршмелоу",

            "Майонез", "Кетчуп", "Гірчиця", "Соєвий соус", "Гострий соус",
            "Оцет", "Маргарин",

            "Кава", "Чорний чай", "Зелений чай", "Какао", "Газовані напої",
            "Енергетичні напої", "Сік пакетований"
        ]


        for product_name in extra_dislike_products:
            products_data.append(
                Product(
                    name=product_name,
                    calories_100g=0,
                    protein_100g=0,
                    fat_100g=0,
                    carbs_100g=0,
                    vit_a_mcg=0,
                    vit_c_mg=0,
                    vit_d_mcg=0,
                    vit_e_mg=0,
                    vit_k_mcg=0,
                    vit_b1_mg=0,
                    vit_b2_mg=0,
                    vit_b6_mg=0,
                    vit_b12_mcg=0,
                    iron_mg=0,
                    calcium_mg=0,
                    magnesium_mg=0,
                    zinc_mg=0
                )
            )

        db.session.add_all(products_data)
        db.session.commit()
        print("Продукти додано.")

        dishes_data = [
            Dish(
                name="Лосось з броколі",
                total_calories=420,
                total_protein=35,
                total_fat=20,
                total_carbs=10,
                vit_a_total=120,
                vit_c_total=90,
                vit_d_total=18,
                vit_e_total=3,
                vit_k_total=90,
                vit_b1_total=0.3,
                vit_b2_total=0.5,
                vit_b6_total=1.0,
                vit_b12_total=3.5,
                iron_total=2,
                calcium_total=80,
                magnesium_total=60,
                zinc_total=1.5,
            ),
            Dish(
                name="Курка з бурим рисом",
                total_calories=500,
                total_protein=35,
                total_fat=10,
                total_carbs=65,
                vit_a_total=20,
                vit_c_total=5,
                vit_d_total=0,
                vit_e_total=1,
                vit_k_total=3,
                vit_b1_total=0.2,
                vit_b2_total=0.2,
                vit_b6_total=0.8,
                vit_b12_total=0.4,
                iron_total=2,
                calcium_total=25,
                magnesium_total=70,
                zinc_total=2,
            ),
            Dish(
                name="Омлет з броколі",
                total_calories=280,
                total_protein=16,
                total_fat=20,
                total_carbs=8,
                vit_a_total=250,
                vit_c_total=60,
                vit_d_total=4,
                vit_e_total=2,
                vit_k_total=80,
                vit_b1_total=0.1,
                vit_b2_total=0.6,
                vit_b6_total=0.2,
                vit_b12_total=1.2,
                iron_total=2,
                calcium_total=90,
                magnesium_total=40,
                zinc_total=1.5,
            ),
            Dish(
                name="Салат зі шпинатом та яйцем",
                total_calories=320,
                total_protein=18,
                total_fat=22,
                total_carbs=5,
                vit_a_total=500,
                vit_c_total=35,
                vit_d_total=4,
                vit_e_total=3,
                vit_k_total=450,
                vit_b1_total=0.1,
                vit_b2_total=0.5,
                vit_b6_total=0.3,
                vit_b12_total=1.2,
                iron_total=4,
                calcium_total=140,
                magnesium_total=100,
                zinc_total=1.8,
            ),
            Dish(
                name="Гречка з куркою",
                total_calories=540,
                total_protein=42,
                total_fat=11,
                total_carbs=67,
                vit_a_total=15,
                vit_c_total=2,
                vit_d_total=0,
                vit_e_total=1,
                vit_k_total=4,
                vit_b1_total=0.4,
                vit_b2_total=0.3,
                vit_b6_total=0.9,
                vit_b12_total=0.4,
                iron_total=4,
                calcium_total=40,
                magnesium_total=120,
                zinc_total=3,
            ),
            Dish(
                name="Вівсянка з бананом і йогуртом",
                total_calories=390,
                total_protein=15,
                total_fat=8,
                total_carbs=65,
                vit_a_total=30,
                vit_c_total=12,
                vit_d_total=0.2,
                vit_e_total=1,
                vit_k_total=3,
                vit_b1_total=0.8,
                vit_b2_total=0.3,
                vit_b6_total=0.5,
                vit_b12_total=0.5,
                iron_total=5,
                calcium_total=180,
                magnesium_total=110,
                zinc_total=3,
            ),
            Dish(
                name="Сир з яблуком",
                total_calories=260,
                total_protein=22,
                total_fat=8,
                total_carbs=25,
                vit_a_total=40,
                vit_c_total=6,
                vit_d_total=0.1,
                vit_e_total=0.5,
                vit_k_total=2,
                vit_b1_total=0.05,
                vit_b2_total=0.4,
                vit_b6_total=0.1,
                vit_b12_total=1.0,
                iron_total=0.5,
                calcium_total=220,
                magnesium_total=25,
                zinc_total=1,
            ),
            Dish(
                name="Овочевий салат з оливковою олією",
                total_calories=230,
                total_protein=4,
                total_fat=15,
                total_carbs=20,
                vit_a_total=700,
                vit_c_total=100,
                vit_d_total=0,
                vit_e_total=5,
                vit_k_total=120,
                vit_b1_total=0.1,
                vit_b2_total=0.1,
                vit_b6_total=0.3,
                vit_b12_total=0,
                iron_total=2,
                calcium_total=70,
                magnesium_total=50,
                zinc_total=0.7,
            ),
            Dish(
                name="Рис з лососем",
                total_calories=560,
                total_protein=34,
                total_fat=22,
                total_carbs=55,
                vit_a_total=60,
                vit_c_total=5,
                vit_d_total=18,
                vit_e_total=3,
                vit_k_total=5,
                vit_b1_total=0.2,
                vit_b2_total=0.5,
                vit_b6_total=0.8,
                vit_b12_total=3.2,
                iron_total=2,
                calcium_total=40,
                magnesium_total=80,
                zinc_total=2,
            ),
            Dish(
                name="Гречка зі шпинатом і яйцем",
                total_calories=430,
                total_protein=24,
                total_fat=15,
                total_carbs=50,
                vit_a_total=450,
                vit_c_total=30,
                vit_d_total=4,
                vit_e_total=2,
                vit_k_total=350,
                vit_b1_total=0.3,
                vit_b2_total=0.5,
                vit_b6_total=0.4,
                vit_b12_total=1.2,
                iron_total=5,
                calcium_total=150,
                magnesium_total=140,
                zinc_total=2,
            ),
        ]

        db.session.add_all(dishes_data)
        db.session.commit()
        print("Страви додано.")

        def p(name):
            return Product.query.filter_by(name=name).first()

        def d(name):
            return Dish.query.filter_by(name=name).first()

        ingredients_data = [
            DishIngredient(dish_id=d("Лосось з броколі").id, product_id=p("Лосось").id, weight_g=150),
            DishIngredient(dish_id=d("Лосось з броколі").id, product_id=p("Броколі").id, weight_g=150),

            DishIngredient(dish_id=d("Курка з бурим рисом").id, product_id=p("Куряче філе").id, weight_g=150),
            DishIngredient(dish_id=d("Курка з бурим рисом").id, product_id=p("Рис бурий").id, weight_g=200),

            DishIngredient(dish_id=d("Омлет з броколі").id, product_id=p("Яйце куряче").id, weight_g=120),
            DishIngredient(dish_id=d("Омлет з броколі").id, product_id=p("Броколі").id, weight_g=100),
            DishIngredient(dish_id=d("Омлет з броколі").id, product_id=p("Оливкова олія").id, weight_g=10),

            DishIngredient(dish_id=d("Салат зі шпинатом та яйцем").id, product_id=p("Шпинат").id, weight_g=100),
            DishIngredient(dish_id=d("Салат зі шпинатом та яйцем").id, product_id=p("Яйце куряче").id, weight_g=100),
            DishIngredient(dish_id=d("Салат зі шпинатом та яйцем").id, product_id=p("Оливкова олія").id, weight_g=10),

            DishIngredient(dish_id=d("Гречка з куркою").id, product_id=p("Гречка").id, weight_g=120),
            DishIngredient(dish_id=d("Гречка з куркою").id, product_id=p("Куряче філе").id, weight_g=150),

            DishIngredient(dish_id=d("Вівсянка з бананом і йогуртом").id, product_id=p("Вівсянка").id, weight_g=70),
            DishIngredient(dish_id=d("Вівсянка з бананом і йогуртом").id, product_id=p("Банан").id, weight_g=100),
            DishIngredient(dish_id=d("Вівсянка з бананом і йогуртом").id, product_id=p("Йогурт натуральний").id, weight_g=150),

            DishIngredient(dish_id=d("Сир з яблуком").id, product_id=p("Сир кисломолочний").id, weight_g=180),
            DishIngredient(dish_id=d("Сир з яблуком").id, product_id=p("Яблуко").id, weight_g=120),

            DishIngredient(dish_id=d("Овочевий салат з оливковою олією").id, product_id=p("Броколі").id, weight_g=80),
            DishIngredient(dish_id=d("Овочевий салат з оливковою олією").id, product_id=p("Перець болгарський").id, weight_g=100),
            DishIngredient(dish_id=d("Овочевий салат з оливковою олією").id, product_id=p("Морква").id, weight_g=80),
            DishIngredient(dish_id=d("Овочевий салат з оливковою олією").id, product_id=p("Оливкова олія").id, weight_g=12),

            DishIngredient(dish_id=d("Рис з лососем").id, product_id=p("Рис бурий").id, weight_g=200),
            DishIngredient(dish_id=d("Рис з лососем").id, product_id=p("Лосось").id, weight_g=150),

            DishIngredient(dish_id=d("Гречка зі шпинатом і яйцем").id, product_id=p("Гречка").id, weight_g=100),
            DishIngredient(dish_id=d("Гречка зі шпинатом і яйцем").id, product_id=p("Шпинат").id, weight_g=80),
            DishIngredient(dish_id=d("Гречка зі шпинатом і яйцем").id, product_id=p("Яйце куряче").id, weight_g=100),
        ]

        db.session.add_all(ingredients_data)
        db.session.commit()
        print("Інгредієнти страв додано.")
        print("Готово! Базу продуктів і страв заповнено.")


if __name__ == "__main__":
    initialize_database()