"""add recipe and ingredients to dishes

Revision ID: 77c083fb1714
Revises: 
Create Date: 2026-05-16 20:08:12.081021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c083fb1714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recipe', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('recipe')
        batch_op.drop_column('ingredients_text')

    # ### end Alembic commands ###
